name: paysecure-ci-cd

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write
  id-token: write

env:
  IMAGE_NAME: paysecure/app
  REGISTRY: ghcr.io

jobs:

  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2

  dependencies-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install safety
      - run: safety check -r requirements.txt

  dependencies-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm audit --audit-level=high

  sast-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install bandit
      - run: bandit -r . -ll

  sast-semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: returntocorp/semgrep-action@v1

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: pytest
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test -- --watchAll=false

  docker-build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t paysecure:latest .

  docker-scan:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: paysecure:latest
          severity: CRITICAL,HIGH
          exit-code: "1"

  sbom:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - uses: actions/checkout@v4
      - uses: anchore/sbom-action@v0

  push:
    runs-on: ubuntu-latest
    needs: docker-scan
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: docker build -t $REGISTRY/$IMAGE_NAME:latest .
      - run: docker push $REGISTRY/$IMAGE_NAME:latest

  deploy:
    runs-on: ubuntu-latest
    needs: push
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::ACCOUNT_ID:role/GitHubDeployRole
          aws-region: eu-west-3
      - run: |
          aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=tag:Name,Values=paysecure-prod" \
          --parameters commands="docker pull ghcr.io/paysecure/app:latest && docker stop paysecure || true && docker rm paysecure || true && docker run -d -p 80:8000 --name paysecure ghcr.io/paysecure/app:latest"